In [2]:
## We work with the dataset scikit-learn

## Determining what you plant based on features

# Imports
import numpy
import sklearn
import sklearn.datasets

# Loads a *dataset* (Irises)
iris = sklearn.datasets.load_iris()

# Get's the recorded observations
# These are 150 observations of
# flowers' sepal and petal
# length and width
X = iris.data

# Print out the shape of the data
print(X.shape)

## If we want to see the different values, we use this
print(X)



(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6

In [3]:
# Gets the labels! for the flowers
# This is like, which classification
# the observation is
y = iris.target
print(y.shape)

## Should contain list of 150 iris, checking the types
print(y)

#X are features, Y is type of the iris

## for this iris, what is the real type?
## YOU cannot write a function, it would take a while
## First Supervised k


(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [10]:
# Import the thing we need
# to make a Knn classifier
## This does all that work
import sklearn.neighbors

# Make the Knn OBJECT
knn = sklearn.neighbors.KNeighborsClassifier()


## Now we will try to understand by to
# This trains the knn on the
# data (X) and labels (y)
knn.fit(X, y)

KNeighborsClassifier()

In [22]:
## We create a new 4D plan after the knn data and labels. You can put any number
new_iris = [[1, 2, 3, 4]]

# new_iris_matrix will be like a
# list of things we want to predict.
# So, ultimately like a list of lists
knn.predict(new_iris)



array([1])

In [24]:
# We need to wrap our one
# question (X[50]) into a list
# because predict wants a list
# of lists to predict
pred = knn.predict([X[50]])
##Is this the same for dataset on y?
print(pred, y[50])

## We need a way to make sure what we learned is the correct information

[1] 1


In [25]:
# This will see what percent
# accuracy the model gets
# with known data X and labels y
acc = knn.score(X,y)
print(acc)

## TO make sure its correct, we should train our dataset on something we didn't train it to do, this would be a better way, we need to seperate 
## Our data into two parts, one for training, and one for testing. There is a method to do it. This says we currently have 96.6% accuracy

0.9666666666666667


In [26]:
import sklearn.model_selection

# Split the X and y into a
# training and testing set
## we wants 75% to learn, and 25% to test for this model
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size=0.25)

## Now we redo everything we do, to test and train



In [27]:
## This is saying this is not as good

knn = sklearn.neighbors.KNeighborsClassifier()
knn.fit(X_train, y_train)
acc = knn.score(X_test, y_test)
print(acc)

## Because you overlearn, it doesn't work as well as if you don't learn as well. We are learning something too specific, because its a little different

0.9736842105263158


In [30]:
## Another method is the Supervised: Support Vector Machines with more information. If it goes too big, it will run too long and it is not as effiecent in 
## learning.

## This trys to draw lines in the plan to seperate them. In a 2D plan we could have lots of points for different types, type 1 and type 2 To not find which one is closer
## To draw a line to seperate them. 2 questions, what side is your line on, by calculation. In terms of code nothing really changes. This is used for lots 
## of information

## Import and load the classifer object, using the same function we used for the coding part

# Import and make a support vector
# classifier object
import sklearn.svm
svc = sklearn.svm.SVC(kernel='linear')

# Train it with the training data
# we already split up
svc.fit(X_train, y_train)

# test it with the testing data
acc = svc.score(X_test, y_test)
print(acc)

## We can use other Sometimes lines are too rigid. We can extend the idea of a linear SVM by using polynomials,
## radial basis functions or some other non-linear *kernel* to do our partitioning.

## Imagine if we didn't have labels for the points put in? All we have is x instead, someone tells you you have two types of flowers? We do we do
## We initialize each type with one point, by calculating using math functions(averages), we calculate if they are close if they are not, we recalculate the averages
## When it is closer we say it is part of the group, to do that, its not really hard

0.9473684210526315


In [35]:
## this is k-mean clustering
import sklearn.cluster
k_means = sklearn.cluster.KMeans(3)
k_means.fit(X)

## we can ask what part of group they are in
labels = k_means.labels_
print(labels)
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
##