In [1]:
## Refresher courses on list

a = ['a', 'b', 'c']
b = [a]

print(len(b))
print(type(b))
## In a copied list you need to identify a first from b, then a's first element
print(b[0][0])

a = ['a','b','c']
b = [a, ['d', 'e', 'f']]

print(len(b))
print(type(b))
print(b[0][0])
##OR
print(b[0][0][0])

## Things get weird here
a = ['a','b','c']
b = [a, a]

print(len(b))
print(type(b))
print(b[0][0])
## This changes both lists at the same position because they are aliases
b[0][0] = 'z'

a = ['a','b','c']
b = [a, ['d', 'e', 'f']]
c = [b, ['g', 'h', 'i']]

print(len(b))
print(len(c))
## you need a third [0] to access the list
print(c[0][0][0])
# A list within a list, where the element is located
print(c)

1
<class 'list'>
a
2
<class 'list'>
a
a
2
<class 'list'>
a
2
2
a
[[['a', 'b', 'c'], ['d', 'e', 'f']], ['g', 'h', 'i']]


In [2]:
# Something new, numpy arrays, there is no commas vs lists that have commas

import numpy
a = numpy.array([5,4,2])
print(a)

## Lets try to change it at position 0

a[0] = 14
print(a)

## Lets replace an element with a string, but it does not work, because with arrays you cannot mix types! Floats get rounded
## down as a failsafe, and if one is a float, then all become floats. All types must be the same!
a[0] = 10.4
print(a)
print(type(a))

## Now lets try operations with 2 numpy arrays

a = numpy.array([5, 4, 2])
b = numpy.array([3, 10, 17])
## This adds the first element of a to the first element of b, then the second element of a to the second element of b, etc.
print(a + b)
## This divides the same way as adding (first by first, second by second, etc)
print(a / b)
## This multiplies the same as the plus (first by first, second by second, etc)
print(a*b)
## This subtracts the same as the plus (first by first, second by second, etc)
print(a-b)

## Basically numpy arrays are mathematically used, for different math operations, but we need to have the same size for each to do
## math operations

## We can ask what type is in the numpy arrays, and tells how many bits it takes to store the array
print(a.dtype)
## We can calculate the mean, and without the () we can find the function address
print(a.mean())
print(a.mean)
## Just press a . after the variable to find the function
## We can add or subtract too all elements using these functions
a += [4]
a -= [6]

print(a)

# This is the append function (like list) for numpy

a.resize(10)
print(a)

## Numpy arrays are for math, and they are your friend for these solutions

## TO SUM EVERY ELEMENT IN AN ARRAY WE DO THIS
def my_sum(a):
  index = 0
  sum = 0
  while index < len(a):
    sum += a[index]
    index += 1
  return sum
## This works for list and numpy arrays
c = [1, 2, 3]
print(my_sum(a))

## Now a 2D array of numpy (MUST BE SAME SIZE!)
a = numpy.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)

#and to get the array size (3 arrays by 3 elements)
print(a.shape)






[5 4 2]
[14  4  2]
[10  4  2]
<class 'numpy.ndarray'>
[ 8 14 19]
[1.66666667 0.4        0.11764706]
[15 40 34]
[  2  -6 -15]
int64
3.6666666666666665
<built-in method mean of numpy.ndarray object at 0x7fa6d27f6810>
[3 2 0]
[3 2 0 0 0 0 0 0 0 0]
5
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
import numpy
arr = numpy.array([0,1,2,3,4,5,6,7])

#To grab different elements, it is much like a list

print(arr[0:3])
print(arr[-3:])
## Creating a 5 by 5 array to make it increment by 1 til 24
a = numpy.arange(25).reshape(5,5)
print(a)
## To print the 3rd colon, it will print each line, but with the comma, we understand we only want a certain element from each row (everything comma second element)
print(a[:,2])
## To print all again, use two colons on each side, you can specify the coordinates in 2D for what element you want.


[0 1 2]
[5 6 7]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 2  7 12 17 22]
